---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.name }} 
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 8 }}
{{- end }}
    spec:
{{ if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{ end }}
{{ if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}    
{{ end }}
      automountServiceAccountToken: false
      priorityClassName: system-node-critical
      containers:
      - name: eks-nvme-provisioner
        image: {{ .Values.image }}
        imagePullPolicy: Always
        securityContext:
          privileged: true
{{ if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{ end }}
        volumeMounts:
          - mountPath: /pv-disks
            name: pv-disks
            mountPropagation: "Bidirectional"
      volumes:
      - name: pv-disks
        hostPath:
          path: /pv-disks
